
#apt purge -y adduser                                 #important
#apt purge -y apt                                     #important
#apt purge -y apt-utils                               #important
#apt purge -y cpio                                    #important
#apt purge -y cron                                    #important
#apt purge -y debconf-i18n                            #important
#apt purge -y dmidecode                               #important
#apt purge -y fdisk                                   #important
#apt purge -y gpgv                                    #important
#apt purge -y groff-base                              #important
#apt purge -y info                                    #important
#apt purge -y init                                    #important
#apt purge -y install-info                            #important
#apt purge -y iproute2                                #important
#apt purge -y iputils-ping                            #important
#apt purge -y isc-dhcp-client                         #important
#apt purge -y isc-dhcp-common                         #important
#apt purge -y kmod                                    #important
#apt purge -y less                                    #important
#apt purge -y libapt-pkg6.0                           #important
#apt purge -y libcap2-bin                             #important
#apt purge -y libffi8                                 #important
#apt purge -y libgnutls30                             #important
#apt purge -y libhogweed6                             #important
#apt purge -y libidn2-0                               #important
#apt purge -y libnettle8                              #important
#apt purge -y libp11-kit0                             #important
#apt purge -y libseccomp2                             #important
#apt purge -y libstdc++6                              #important
#apt purge -y libtasn1-6                              #important
#apt purge -y libunistring2                           #important
#apt purge -y libxxhash0                              #important
#apt purge -y logrotate                               #important
#apt purge -y man-db                                  #important
#apt purge -y nano                                    #important
#apt purge -y netbase                                 #important
#apt purge -y netcat-openbsd                          #important
#apt purge -y nftables                                #important
#apt purge -y rsyslog                                 #important
#apt purge -y systemd                                 #important
#apt purge -y systemd-resolved                        #important
#apt purge -y systemd-sysv                            #important
#apt purge -y ubuntu-advantage-tools                  #important
#apt purge -y ubuntu-keyring                          #important
#apt purge -y udev                                    #important
#apt purge -y vim-common                              #important
#apt purge -y vim-tiny                                #important
