apt purge -y apache2-utils                           #optional
#apt purge -y apparmor                                #optional
apt purge -y apport                                  #optional
apt purge -y apport-symptoms                         #optional
#apt purge -y bcache-tools                            #optional
#apt purge -y binutils                                #optional
#apt purge -y binutils-common                         #optional
#apt purge -y binutils-x86-64-linux-gnu               #optional
apt purge -y bolt                                    #optional
#apt purge -y bsdextrautils                           #optional
apt purge -y btrfs-progs                             #optional
#apt purge -y build-essential                         #optional
#apt purge -y busybox-initramfs                       #optional
#apt purge -y busybox-static                          #optional
#apt purge -y byobu                                   #optional
apt purge -y cloud-guest-utils                       #optional
apt purge -y cloud-initramfs-copymods                #optional
apt purge -y cloud-initramfs-dyn-netconf             #optional
apt purge -y cmake                                   #optional
#apt purge -y cmake-data                              #optional
#apt purge -y command-not-found                       #optional
#apt purge -y console-setup                           #optional
#apt purge -y console-setup-linux                     #optional
apt purge -y cpp                                     #optional
apt purge -y cpp-12                                  #optional
#apt purge -y cracklib-runtime                        #optional
#apt purge -y cryptsetup                              #optional
#apt purge -y cryptsetup-bin                          #optional
#apt purge -y cryptsetup-initramfs                    #optional
#apt purge -y curl                                    #optional
#apt purge -y dbus-bin                                #optional
#apt purge -y dbus-daemon                             #optional
#apt purge -y dbus-session-bus-common                 #optional
#apt purge -y dbus-system-bus-common                  #optional
#apt purge -y dbus-user-session                       #optional
#apt purge -y dh-elpa-helper                          #optional
#apt purge -y dirmngr                                 #optional
#apt purge -y distro-info                             #optional
#apt purge -y distro-info-data                        #optional
#apt purge -y dmeventd                                #optional
#apt purge -y dmsetup                                 #optional
#apt purge -y dosfstools                              #optional
#apt purge -y dpkg-dev                                #optional
#apt purge -y eatmydata                               #optional
#apt purge -y ed                                      #optional
#apt purge -y eject                                   #optional
apt purge -y emacsen-common                          #optional
#apt purge -y ethtool                                 #optional
#apt purge -y fakeroot                                #optional
#apt purge -y finalrd                                 #optional
#apt purge -y firmware-sof-signed                     #optional
apt purge -y fontconfig-config                       #optional
apt purge -y fonts-dejavu-core                       #optional
apt purge -y fonts-ubuntu-console                    #optional
#apt purge -y friendly-recovery                       #optional
#apt purge -y ftp                                     #optional
apt purge -y fuse3                                   #optional
#apt purge -y fwupd                                   #optional
#apt purge -y fwupd-signed                            #optional
apt purge -y g++                                     #optional
apt purge -y g++-12                                  #optional
#apt purge -y gawk                                    #optional
#apt purge -y gcc                                     #optional
#apt purge -y gcc-12                                  #optional
#apt purge -y gdisk                                   #optional
#apt purge -y gir1.2-glib-2.0                         #optional
#apt purge -y gir1.2-packagekitglib-1.0               #optional
#apt purge -y git                                     #optional
#apt purge -y git-man                                 #optional
#apt purge -y gnupg                                   #optional
#apt purge -y gnupg2                                  #optional
#apt purge -y gnupg-l10n                              #optional
#apt purge -y gnupg-utils                             #optional
#apt purge -y gpg                                     #optional
#apt purge -y gpg-agent                               #optional
#apt purge -y gpgconf                                 #optional
#apt purge -y gpgsm                                   #optional
#apt purge -y gpg-wks-client                          #optional
#apt purge -y gpg-wks-server                          #optional
#apt purge -y grub2-common                            #optional
#apt purge -y grub-common                             #optional
#apt purge -y grub-gfxpayload-lists                   #optional
#apt purge -y grub-pc                                 #optional
#apt purge -y grub-pc-bin                             #optional
#apt purge -y hdparm                                  #optional
apt purge -y htop                                    #optional
#apt purge -y initramfs-tools                         #optional
#apt purge -y initramfs-tools-bin                     #optional
#apt purge -y initramfs-tools-core                    #optional
apt purge -y iptables                                #optional
apt purge -y iputils-tracepath                       #optional
#apt purge -y irqbalance                              #optional
#apt purge -y iso-codes                               #optional
#apt purge -y iucode-tool                             #optional
apt purge -y javascript-common                       #optional
#apt purge -y jq                                      #optional
#apt purge -y kbd                                     #optional
#apt purge -y keyboard-configuration                  #optional
#apt purge -y klibc-utils                             #optional
#apt purge -y kpartx                                  #optional
#apt purge -y krb5-locales                            #optional
#apt purge -y landscape-common                        #optional
#apt purge -y libaio1                                 #optional
#apt purge -y libalgorithm-diff-perl                  #optional
#apt purge -y libalgorithm-diff-xs-perl               #optional
#apt purge -y libalgorithm-merge-perl                 #optional
#apt purge -y libapparmor1                            #optional
#apt purge -y libappstream4                           #optional
#apt purge -y libapr1                                 #optional
#apt purge -y libaprutil1                             #optional
#apt purge -y libarchive13                            #optional
#apt purge -y libargon2-1                             #optional
#apt purge -y libasan8                                #optional
#apt purge -y libassuan0                              #optional
#apt purge -y libatasmart4                            #optional
#apt purge -y libatm1                                 #optional
#apt purge -y libatomic1                              #optional
#apt purge -y libbinutils                             #optional
#apt purge -y libblockdev2                            #optional
#apt purge -y libblockdev-crypto2                     #optional
#apt purge -y libblockdev-fs2                         #optional
#apt purge -y libblockdev-loop2                       #optional
#apt purge -y libblockdev-part2                       #optional
#apt purge -y libblockdev-part-err2                   #optional
#apt purge -y libblockdev-swap2                       #optional
#apt purge -y libblockdev-utils2                      #optional
#apt purge -y libbpf0                                 #optional
#apt purge -y libbrotli1                              #optional
#apt purge -y libbsd0                                 #optional
#apt purge -y libc6-dev                               #optional
#apt purge -y libcbor0.8                              #optional
#apt purge -y libcc1-0                                #optional
#apt purge -y libc-dev-bin                            #optional
#apt purge -y libc-devtools                           #optional
#apt purge -y libcrack2                               #optional
#apt purge -y libcrypt-dev                            #optional
#apt purge -y libcryptsetup12                         #optional
#apt purge -y libctf0                                 #optional
#apt purge -y libctf-nobfd0                           #optional
#apt purge -y libcurl3-gnutls                         #optional
#apt purge -y libcurl4                                #optional
#apt purge -y libdbus-1-3                             #optional
#apt purge -y libdbus-glib-1-2                        #optional
#apt purge -y libdeflate0                             #optional
#apt purge -y libdevmapper1.02.1                      #optional
#apt purge -y libdevmapper-event1.02.1                #optional
#apt purge -y libdpkg-perl                            #optional
#apt purge -y libdrm2                                 #optional
#apt purge -y libdrm-amdgpu1                          #optional
#apt purge -y libdrm-common                           #optional
#apt purge -y libdrm-intel1                           #optional
#apt purge -y libdrm-nouveau2                         #optional
#apt purge -y libdrm-radeon1                          #optional
#apt purge -y libdw1                                  #optional
#apt purge -y libeatmydata1                           #optional
#apt purge -y libedit2                                #optional
#apt purge -y libefiboot1                             #optional
#apt purge -y libefivar1                              #optional
#apt purge -y libegl1                                 #optional
#apt purge -y libegl-dev                              #optional
#apt purge -y libegl-mesa0                            #optional
#apt purge -y libelf1                                 #optional
#apt purge -y liberror-perl                           #optional
#apt purge -y libestr0                                #optional
#apt purge -y libevdev2                               #optional
#apt purge -y libevent-core-2.1-7a                    #optional
#apt purge -y libexpat1                               #optional
#apt purge -y libexpat1-dev                           #optional
#apt purge -y libfakeroot                             #optional
#apt purge -y libfastjson4                            #optional
#apt purge -y libfdisk1                               #optional
#apt purge -y libfido2-1                              #optional
#apt purge -y libfile-fcntllock-perl                  #optional
#apt purge -y libflashrom1                            #optional
#apt purge -y libfontconfig1                          #optional
#apt purge -y libfreetype6                            #optional
#apt purge -y libfribidi0                             #optional
#apt purge -y libftdi1-2                              #optional
#apt purge -y libfuse3-3                              #optional
#apt purge -y libfwupd2                               #optional
#apt purge -y libfwupdplugin7                         #optional
#apt purge -y libgbm1                                 #optional
#apt purge -y libgcab-1.0-0                           #optional
#apt purge -y libgcc-12-dev                           #optional
#apt purge -y libgd3                                  #optional
#apt purge -y libgdbm6                                #optional
#apt purge -y libgdbm-compat4                         #optional
#apt purge -y libgfortran5                            #optional
#apt purge -y libgirepository-1.0-1                   #optional
#apt purge -y libgl1                                  #optional
#apt purge -y libgl1-amber-dri                        #optional
#apt purge -y libgl1-mesa-dri                         #optional
#apt purge -y libglapi-mesa                           #optional
#apt purge -y libgl-dev                               #optional
#apt purge -y libgles1                                #optional
#apt purge -y libgles2                                #optional
#apt purge -y libgles-dev                             #optional
#apt purge -y libglib2.0-0                            #optional
#apt purge -y libglib2.0-bin                          #optional
#apt purge -y libglib2.0-data                         #optional
#apt purge -y libglvnd0                               #optional
#apt purge -y libglvnd-core-dev                       #optional
#apt purge -y libglvnd-dev                            #optional
#apt purge -y libglx0                                 #optional
#apt purge -y libglx-dev                              #optional
#apt purge -y libglx-mesa0                            #optional
#apt purge -y libgomp1                                #optional
#apt purge -y libgpgme11                              #optional
#apt purge -y libgpm2                                 #optional
#apt purge -y libgprofng0                             #optional
#apt purge -y libgssapi-krb5-2                        #optional
#apt purge -y libgstreamer1.0-0                       #optional
#apt purge -y libgudev-1.0-0                          #optional
#apt purge -y libgusb2                                #optional
#apt purge -y libicu71                                #optional
#apt purge -y libinih1                                #optional
#apt purge -y libintl-perl                            #optional
#apt purge -y libintl-xs-perl                         #optional
#apt purge -y libip4tc2                               #optional
#apt purge -y libip6tc2                               #optional
#apt purge -y libisl23                                #optional
#apt purge -y libisns0                                #optional
#apt purge -y libitm1                                 #optional
#apt purge -y libjansson4                             #optional
#apt purge -y libjbig0                                #optional
#apt purge -y libjcat1                                #optional
#apt purge -y libjpeg8                                #optional
#apt purge -y libjpeg-turbo8                          #optional
#apt purge -y libjq1                                  #optional
#apt purge -y libjs-jquery                            #optional
#apt purge -y libjson-c5                              #optional
#apt purge -y libjsoncpp25                            #optional
#apt purge -y libjson-glib-1.0-0                      #optional
#apt purge -y libjson-glib-1.0-common                 #optional
#apt purge -y libjs-sphinxdoc                         #optional
#apt purge -y libjs-underscore                        #optional
#apt purge -y libk5crypto3                            #optional
#apt purge -y libkeyutils1                            #optional
#apt purge -y libklibc                                #optional
#apt purge -y libkmod2                                #optional
#apt purge -y libkrb5-3                               #optional
#apt purge -y libkrb5support0                         #optional
#apt purge -y libksba8                                #optional
#apt purge -y liblapack3                              #optional
#apt purge -y liblapack-dev                           #optional
#apt purge -y libldap-2.5-0                           #optional
#apt purge -y libldap-common                          #optional
#apt purge -y liblerc3                                #optional
#apt purge -y libllvm15                               #optional
#apt purge -y liblmdb0                                #optional
#apt purge -y liblsan0                                #optional
#apt purge -y liblvm2cmd2.03                          #optional
#apt purge -y liblzo2-2                               #optional
#apt purge -y libmagic1                               #optional
#apt purge -y libmagic-mgc                            #optional
#apt purge -y libmaxminddb0                           #optional
#apt purge -y libmbim-glib4                           #optional
#apt purge -y libmbim-proxy                           #optional
#apt purge -y libmd0                                  #optional
#apt purge -y libmm-glib0                             #optional
#apt purge -y libmnl0                                 #optional
#apt purge -y libmodule-find-perl                     #optional
#apt purge -y libmodule-scandeps-perl                 #optional
#apt purge -y libmpc3                                 #optional
#apt purge -y libmpdec3                               #optional
#apt purge -y libmpfr6                                #optional
#apt purge -y libmspack0                              #optional
#apt purge -y libnetfilter-conntrack3                 #optional
#apt purge -y libnetplan0                             #optional
#apt purge -y libnewt0.52                             #optional
#apt purge -y libnfnetlink0                           #optional
#apt purge -y libnftables1                            #optional
#apt purge -y libnftnl11                              #optional
#apt purge -y libnghttp2-14                           #optional
#apt purge -y libnl-3-200                             #optional
#apt purge -y libnl-genl-3-200                        #optional
#apt purge -y libnpth0                                #optional
#apt purge -y libnsl2                                 #optional
#apt purge -y libnsl-dev                              #optional
#apt purge -y libnspr4                                #optional
#apt purge -y libnss3                                 #optional
#apt purge -y libntfs-3g89                            #optional
#apt purge -y libnuma1                                #optional
#apt purge -y libonig5                                #optional
#apt purge -y libopenblas0                            #optional
#apt purge -y libopenblas0-pthread                    #optional
#apt purge -y libopenblas-dev                         #optional
#apt purge -y libopenblas-pthread-dev                 #optional
#apt purge -y libopengl0                              #optional
#apt purge -y libopengl-dev                           #optional
#apt purge -y libopeniscsiusr                         #optional
#apt purge -y libpackagekit-glib2-18                  #optional
#apt purge -y libpam-cap                              #optional
#apt purge -y libpam-pwquality                        #optional
#apt purge -y libparted2                              #optional
#apt purge -y libparted-fs-resize0                    #optional
#apt purge -y libpcap0.8                              #optional
#apt purge -y libpci3                                 #optional
#apt purge -y libpciaccess0                           #optional
#apt purge -y libperl5.34                             #optional
#apt purge -y libpipeline1                            #optional
#apt purge -y libplymouth5                            #optional
#apt purge -y libpng16-16                             #optional
#apt purge -y libpolkit-agent-1-0                     #optional
#apt purge -y libpolkit-gobject-1-0                   #optional
#apt purge -y libpopt0                                #optional
#apt purge -y libproc-processtable-perl               #optional
#apt purge -y libprotobuf-c1                          #optional
#apt purge -y libpsl5                                 #optional
#apt purge -y libpthread-stubs0-dev                   #optional
#apt purge -y libpwquality1                           #optional
#apt purge -y libpwquality-common                     #optional
apt purge -y libpython3.10                           #optional
apt purge -y libpython3.10-dev                       #optional
apt purge -y libpython3.10-minimal                   #optional
apt purge -y libpython3.10-stdlib                    #optional
apt purge -y libpython3-dev                          #optional
apt purge -y libpython3-stdlib                       #optional
#apt purge -y libqmi-glib5                            #optional
#apt purge -y libqmi-proxy                            #optional
#apt purge -y libquadmath0                            #optional
#apt purge -y libreadline8                            #optional
#apt purge -y librhash0                               #optional
#apt purge -y librtmp1                                #optional
#apt purge -y libsasl2-2                              #optional
#apt purge -y libsasl2-modules                        #optional
#apt purge -y libsasl2-modules-db                     #optional
#apt purge -y libsensors5                             #optional
#apt purge -y libsensors-config                       #optional
#apt purge -y libsgutils2-2                           #optional
#apt purge -y libsigsegv2                             #optional
#apt purge -y libslang2                               #optional
#apt purge -y libsmbios-c2                            #optional
#apt purge -y libsodium23                             #optional
#apt purge -y libsort-naturally-perl                  #optional
#apt purge -y libsqlite3-0                            #optional
#apt purge -y libssh-4                                #optional
#apt purge -y libssl3                                 #optional
#apt purge -y libstdc++-12-dev                        #optional
#apt purge -y libstemmer0d                            #optional
#apt purge -y libsystemd-shared                       #optional
#apt purge -y libtcl8.6                               #optional
#apt purge -y libterm-readkey-perl                    #optional
#apt purge -y libtiff5                                #optional
#apt purge -y libtirpc3                               #optional
#apt purge -y libtirpc-common                         #optional
#apt purge -y libtirpc-dev                            #optional
#apt purge -y libtsan2                                #optional
#apt purge -y libtss2-esys-3.0.2-0                    #optional
#apt purge -y libtss2-mu0                             #optional
#apt purge -y libtss2-sys1                            #optional
#apt purge -y libtss2-tcti-cmd0                       #optional
#apt purge -y libtss2-tcti-device0                    #optional
#apt purge -y libtss2-tcti-mssim0                     #optional
#apt purge -y libtss2-tcti-swtpm0                     #optional
#apt purge -y libubsan1                               #optional
#apt purge -y libuchardet0                            #optional
#apt purge -y libudisks2-0                            #optional
#apt purge -y libunwind8                              #optional
#apt purge -y libupower-glib3                         #optional
#apt purge -y liburcu8                                #optional
#apt purge -y liburing2                               #optional
#apt purge -y libusb-1.0-0                            #optional
#apt purge -y libutempter0                            #optional
#apt purge -y libuv1                                  #optional
#apt purge -y libvolume-key1                          #optional
#apt purge -y libwayland-client0                      #optional
#apt purge -y libwayland-server0                      #optional
#apt purge -y libwebp7                                #optional
#apt purge -y libwrap0                                #optional
apt purge -y libx11-6                                #optional
apt purge -y libx11-data                             #optional
apt purge -y libx11-dev                              #optional
apt purge -y libx11-xcb1                             #optional
#apt purge -y libxau6                                 #optional
#apt purge -y libxau-dev                              #optional
#apt purge -y libxcb1                                 #optional
#apt purge -y libxcb1-dev                             #optional
#apt purge -y libxcb-dri2-0                           #optional
#apt purge -y libxcb-dri3-0                           #optional
#apt purge -y libxcb-glx0                             #optional
#apt purge -y libxcb-present0                         #optional
#apt purge -y libxcb-shm0                             #optional
#apt purge -y libxcb-sync1                            #optional
#apt purge -y libxcb-xfixes0                          #optional
#apt purge -y libxdmcp6                               #optional
#apt purge -y libxdmcp-dev                            #optional
#apt purge -y libxext6                                #optional
#apt purge -y libxfixes3                              #optional
#apt purge -y libxml2                                 #optional
#apt purge -y libxmlb2                                #optional
#apt purge -y libxmlsec1                              #optional
#apt purge -y libxmlsec1-openssl                      #optional
#apt purge -y libxmuu1                                #optional
#apt purge -y libxpm4                                 #optional
#apt purge -y libxshmfence1                           #optional
#apt purge -y libxslt1.1                              #optional
#apt purge -y libxtables12                            #optional
#apt purge -y libxxf86vm1                             #optional
#apt purge -y libyaml-0-2                             #optional
#apt purge -y linux-base                              #optional
#apt purge -y linux-firmware                          #optional
#apt purge -y linux-generic                           #optional
#apt purge -y linux-headers-5.19.0-23                 #optional
#apt purge -y linux-headers-5.19.0-23-generic         #optional
#apt purge -y linux-headers-generic                   #optional
#apt purge -y linux-image-5.19.0-23-generic           #optional
#apt purge -y linux-image-generic                     #optional
#apt purge -y linux-libc-dev                          #optional
#apt purge -y linux-modules-5.19.0-23-generic         #optional
#apt purge -y linux-modules-extra-5.19.0-23-generic   #optional
#apt purge -y lsb-release                             #optional
#apt purge -y lshw                                    #optional
#apt purge -y lto-disabled-list                       #optional
#apt purge -y lvm2                                    #optional
apt purge -y lxd-agent-loader                        #optional
#apt purge -y make                                    #optional
apt purge -y manpages-dev                            #optional
#apt purge -y mdadm                                   #optional
#apt purge -y mlocate                                 #optional
#apt purge -y modemmanager                            #optional
#apt purge -y motd-news-config                        #optional
#apt purge -y mtr-tiny                                #optional
#apt purge -y multipath-tools                         #optional
#apt purge -y needrestart                             #optional
#apt purge -y netkit-telnet                           #optional
#apt purge -y netplan.io                              #optional
#apt purge -y networkd-dispatcher                     #optional
#apt purge -y ntfs-3g                                 #optional
#apt purge -y open-iscsi                              #optional
#apt purge -y openssh-server                          #optional
#apt purge -y openssh-sftp-server                     #optional
#apt purge -y openssl                                 #optional
#apt purge -y open-vm-tools                           #optional
#apt purge -y os-prober                               #optional
#apt purge -y overlayroot                             #optional
#apt purge -y packagekit                              #optional
#apt purge -y packagekit-tools                        #optional
#apt purge -y parted                                  #optional
#apt purge -y pastebinit                              #optional
#apt purge -y patch                                   #optional
#apt purge -y pci.ids                                 #optional
#apt purge -y pinentry-curses                         #optional
#apt purge -y pkexec                                  #optional
#apt purge -y pkg-config                              #optional
#apt purge -y plocate                                 #optional
#apt purge -y plymouth                                #optional
#apt purge -y plymouth-theme-ubuntu-text              #optional
#apt purge -y policykit-1                             #optional
#apt purge -y polkitd                                 #optional
#apt purge -y pollinate                               #optional
#apt purge -y powermgmt-base                          #optional
#apt purge -y psmisc                                  #optional
#apt purge -y publicsuffix                            #optional
apt purge -y python3                                 #optional
apt purge -y python3.10                              #optional
apt purge -y python3.10-dev                          #optional
apt purge -y python3.10-minimal                      #optional
apt purge -y python3-apport                          #optional
apt purge -y python3-apt                             #optional
apt purge -y python3-attr                            #optional
apt purge -y python3-automat                         #optional
apt purge -y python3-babel                           #optional
apt purge -y python3-bcrypt                          #optional
apt purge -y python3-blinker                         #optional
apt purge -y python3-certifi                         #optional
apt purge -y python3-cffi-backend                    #optional
apt purge -y python3-chardet                         #optional
apt purge -y python3-click                           #optional
apt purge -y python3-colorama                        #optional
apt purge -y python3-commandnotfound                 #optional
apt purge -y python3-configobj                       #optional
apt purge -y python3-constantly                      #optional
apt purge -y python3-cryptography                    #optional
apt purge -y python3-dbus                            #optional
apt purge -y python3-debconf                         #optional
apt purge -y python3-debian                          #optional
apt purge -y python3-dev                             #optional
apt purge -y python3-distro                          #optional
apt purge -y python3-distro-info                     #optional
apt purge -y python3-distupgrade                     #optional
apt purge -y python3-distutils                       #optional
apt purge -y python3-gdbm                            #optional
apt purge -y python3-gi                              #optional
apt purge -y python3-hamcrest                        #optional
apt purge -y python3-httplib2                        #optional
apt purge -y python3-hyperlink                       #optional
apt purge -y python3-idna                            #optional
apt purge -y python3-importlib-metadata              #optional
apt purge -y python3-incremental                     #optional
apt purge -y python3-jeepney                         #optional
apt purge -y python3-jinja2                          #optional
apt purge -y python3-jsonpatch                       #optional
apt purge -y python3-json-pointer                    #optional
apt purge -y python3-jsonschema                      #optional
apt purge -y python3-jwt                             #optional
apt purge -y python3-keyring                         #optional
apt purge -y python3-launchpadlib                    #optional
apt purge -y python3-lazr.restfulclient              #optional
apt purge -y python3-lazr.uri                        #optional
apt purge -y python3-lib2to3                         #optional
apt purge -y python3-magic                           #optional
apt purge -y python3-markupsafe                      #optional
apt purge -y python3-minimal                         #optional
apt purge -y python3-more-itertools                  #optional
apt purge -y python3-netifaces                       #optional
apt purge -y python3-newt                            #optional
apt purge -y python3-oauthlib                        #optional
apt purge -y python3-openssl                         #optional
apt purge -y python3-pexpect                         #optional
apt purge -y python3-pip                             #optional
apt purge -y python3-pkg-resources                   #optional
apt purge -y python3-problem-report                  #optional
apt purge -y python3-ptyprocess                      #optional
apt purge -y python3-pyasn1                          #optional
apt purge -y python3-pyasn1-modules                  #optional
apt purge -y python3-pyparsing                       #optional
apt purge -y python3-pyrsistent                      #optional
apt purge -y python3-requests                        #optional
apt purge -y python3-secretstorage                   #optional
apt purge -y python3-serial                          #optional
apt purge -y python3-service-identity                #optional
apt purge -y python3-setuptools                      #optional
apt purge -y python3-six                             #optional
apt purge -y python3-software-properties             #optional
apt purge -y python3-systemd                         #optional
apt purge -y python3-twisted                         #optional
apt purge -y python3-tz                              #optional
apt purge -y python3-update-manager                  #optional
apt purge -y python3-urllib3                         #optional
apt purge -y python3-wadllib                         #optional
apt purge -y python3-wheel                           #optional
apt purge -y python3-xkit                            #optional
apt purge -y python3-yaml                            #optional
apt purge -y python3-zipp                            #optional
apt purge -y python3-zope.interface                  #optional
apt purge -y python-apt-common                       #optional
apt purge -y python-babel-localedata                 #optional
#apt purge -y readline-common                         #optional
#apt purge -y rpcsvc-proto                            #optional
#apt purge -y rsync                                   #optional
#apt purge -y run-one                                 #optional
#apt purge -y sbsigntool                              #optional
#apt purge -y secureboot-db                           #optional
#apt purge -y sg3-utils                               #optional
#apt purge -y sg3-utils-udev                          #optional
#apt purge -y sgml-base                               #optional
#apt purge -y shared-mime-info                        #optional
apt purge -y snapd                                   #optional
#apt purge -y software-properties-common              #optional
#apt purge -y sosreport                               #optional
#apt purge -y squashfs-tools                          #optional
#apt purge -y ssh-import-id                           #optional
#apt purge -y strace                                  #optional
#apt purge -y sudo                                    #optional
#apt purge -y systemd-hwe-hwdb                        #optional
#apt purge -y tcl                                     #optional
#apt purge -y tcl8.6                                  #optional
#apt purge -y tcpdump                                 #optional
#apt purge -y thermald                                #optional
#apt purge -y thin-provisioning-tools                 #optional
#apt purge -y tmux                                    #optional
#apt purge -y tnftp                                   #optional
#apt purge -y tpm-udev                                #optional
#apt purge -y ubuntu-drivers-common                   #optional
#apt purge -y ubuntu-minimal                          #optional
#apt purge -y ubuntu-release-upgrader-core            #optional
#apt purge -y ubuntu-server                           #optional
apt purge -y ubuntu-standard                         #optional
#apt purge -y udisks2                                 #optional
#apt purge -y ufw                                     #optional
#apt purge -y unattended-upgrades                     #optional
#apt purge -y unzip                                   #optional
#apt purge -y update-manager-core                     #optional
#apt purge -y update-notifier-common                  #optional
#apt purge -y upower                                  #optional
#apt purge -y usb.ids                                 #optional
#apt purge -y usb-modeswitch                          #optional
#apt purge -y usb-modeswitch-data                     #optional
#apt purge -y usbutils                                #optional
#apt purge -y uuid-runtime                            #optional
apt purge -y vim                                     #optional
apt purge -y vim-runtime                             #optional
#apt purge -y whiptail                                #optional
apt purge -y wireless-regdb                          #optional
apt purge -y x11proto-dev                            #optional
#apt purge -y xauth                                   #optional
#apt purge -y xdg-user-dirs                           #optional
#apt purge -y xfsprogs                                #optional
#apt purge -y xkb-data                                #optional
apt purge -y xorg-sgml-doctools                      #optional
#apt purge -y xtrans-dev                              #optional
#apt purge -y xxd                                     #optional
#apt purge -y zerofree                                #optional
#apt purge -y zip                                     #optional
#apt purge -y zlib1g-dev                              #optional
#apt purge -y zstd                                    #optional
