
#apt purge -y base-files                              #required
#apt purge -y base-passwd                             #required
#apt purge -y bash                                    #required
#apt purge -y bsdutils                                #required
#apt purge -y coreutils                               #required
#apt purge -y dash                                    #required
#apt purge -y debconf                                 #required
#apt purge -y debianutils                             #required
#apt purge -y diffutils                               #required
#apt purge -y dpkg                                    #required
#apt purge -y e2fsprogs                               #required
#apt purge -y findutils                               #required
#apt purge -y gcc-12-base                             #required
#apt purge -y grep                                    #required
#apt purge -y gzip                                    #required
#apt purge -y hostname                                #required
#apt purge -y init-system-helpers                     #required
#apt purge -y libacl1                                 #required
#apt purge -y libattr1                                #required
#apt purge -y libaudit1                               #required
#apt purge -y libaudit-common                         #required
#apt purge -y libblkid1                               #required
#apt purge -y libbz2-1.0                              #required
#apt purge -y libc6                                   #required
#apt purge -y libcap2                                 #required
#apt purge -y libcap-ng0                              #required
#apt purge -y libc-bin                                #required
#apt purge -y libcom-err2                             #required
#apt purge -y libcrypt1                               #required
#apt purge -y libdb5.3                                #required
#apt purge -y libdebconfclient0                       #required
#apt purge -y libext2fs2                              #required
#apt purge -y libgcc-s1                               #required
#apt purge -y libgcrypt20                             #required
#apt purge -y libgmp10                                #required
#apt purge -y libgpg-error0                           #required
#apt purge -y liblocale-gettext-perl                  #required
#apt purge -y liblz4-1                                #required
#apt purge -y liblzma5                                #required
#apt purge -y libmount1                               #required
#apt purge -y libncurses6                             #required
#apt purge -y libncursesw6                            #required
#apt purge -y libpam0g                                #required
#apt purge -y libpam-modules                          #required
#apt purge -y libpam-modules-bin                      #required
#apt purge -y libpam-runtime                          #required
#apt purge -y libpcre2-8-0                            #required
#apt purge -y libpcre3                                #required
#apt purge -y libprocps8                              #required
#apt purge -y libselinux1                             #required
#apt purge -y libsemanage2                            #required
#apt purge -y libsemanage-common                      #required
#apt purge -y libsepol2                               #required
#apt purge -y libsmartcols1                           #required
#apt purge -y libss2                                  #required
#apt purge -y libsystemd0                             #required
#apt purge -y libtext-charwidth-perl                  #required
#apt purge -y libtext-iconv-perl                      #required
#apt purge -y libtext-wrapi18n-perl                   #required
#apt purge -y libtinfo6                               #required
#apt purge -y libudev1                                #required
#apt purge -y libuuid1                                #required
#apt purge -y libzstd1                                #required
#apt purge -y login                                   #required
#apt purge -y logsave                                 #required
#apt purge -y lsb-base                                #required
#apt purge -y mawk                                    #required
#apt purge -y mount                                   #required
#apt purge -y ncurses-base                            #required
#apt purge -y ncurses-bin                             #required
#apt purge -y passwd                                  #required
#apt purge -y perl-base                               #required
#apt purge -y procps                                  #required
#apt purge -y sed                                     #required
#apt purge -y sensible-utils                          #required
#apt purge -y sysvinit-utils                          #required
#apt purge -y tar                                     #required
#apt purge -y tzdata                                  #required
#apt purge -y usrmerge                                #required
#apt purge -y util-linux                              #required
#apt purge -y util-linux-extra                        #required
#apt purge -y zlib1g                                  #required
