
#apt purge -y amd64-microcode                         #standard
#apt purge -y bash-completion                         #standard
#apt purge -y bc                                      #standard
#apt purge -y bind9-dnsutils                          #standard
#apt purge -y bind9-host                              #standard
#apt purge -y bind9-libs                              #standard
#apt purge -y bzip2                                   #standard
#apt purge -y ca-certificates                         #standard
#apt purge -y dbus                                    #standard
#apt purge -y file                                    #standard
#apt purge -y gettext-base                            #standard
#apt purge -y intel-microcode                         #standard
#apt purge -y libnss-systemd                          #standard
#apt purge -y libpam-systemd                          #standard
#apt purge -y locales                                 #standard
#apt purge -y lsof                                    #standard
apt purge -y manpages                                #standard
#apt purge -y media-types                             #standard
#apt purge -y ncurses-term                            #standard
#apt purge -y openssh-client                          #standard
#apt purge -y pciutils                                #standard
apt purge -y perl                                    #standard
apt purge -y perl-modules-5.34                       #standard
apt purge -y screen                                  #standard
#apt purge -y systemd-timesyncd                       #standard
#apt purge -y time                                    #standard
#apt purge -y ucf                                     #standard
#apt purge -y wamerican                               #standard
#apt purge -y wget                                    #standard
#apt purge -y xz-utils                                #standard
